profileextension PX16 extends "PRESIDENT"
{
    ProfileDescription = 'Generated by layout tool';
    Customizations = PC16;
}

pagecustomization PC16 customizes "Company Information"
{
    layout
    {
        modify("Bank Name")
        {
            Visible = false;
        }

    }
}
