profileextension PX17 extends "PRESIDENT"
{
    ProfileDescription = 'Generated by layout tool';
    Customizations = PC17;
}

pagecustomization PC17 customizes "Customer Card"
{
    layout
    {
        modify(Name)
        {
            Visible = false;
        }

    }
}
