profileextension PX18 extends "PRESIDENT"
{
    ProfileDescription = 'Generated by layouttool';
    Customizations = PC18;
}

pagecustomization PC18 customizes "Item Ledger Entries"
{
    layout
    {
        modify("Item No.")
        {
            Visible = false;
        }

    }
}
