name: "Publish To Environment"

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to deploy to environment(s) (current, prerelease, draft, latest, version number or PR_<PR Id>)
        required: false
        default: 'current'
      environmentName:
        description: Environment mask to receive the new version (* for all, PROD* for all environments starting with PROD)
        required: true

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  secrets: ${{ vars.ALGoUsedSecrets }}

jobs:
  Initialization:
    runs-on: windows-latest
    outputs:
      deploymentEnvironmentsJson: ${{ steps.SetOutputs.outputs.deploymentEnvironmentsJson }}
      environmentMatrixJson: ${{ steps.SetOutputs.outputs.environmentMatrixJson }}
    steps:
      - name: Read settings
        id: ReadSettings
        uses: microsoft/AL-Go-Actions/ReadSettings@v7.2

      - name: Set deployment outputs
        id: SetOutputs
        run: |
          echo "deploymentEnvironmentsJson=${{ toJson(fromJson(steps.ReadSettings.outputs.deploymentEnvironments)) }}" >> $GITHUB_OUTPUT
          echo "environmentMatrixJson=${{ toJson(fromJson(steps.ReadSettings.outputs.environmentsMatrix)) }}" >> $GITHUB_OUTPUT

  Deploy:
    name: Deploy to ${{ matrix.environment }}
    needs: Initialization
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJson(needs.Initialization.outputs.environmentMatrixJson) }}
    steps:
      - name: Deploy App to ${{ matrix.environment }}
        uses: microsoft/AL-Go-Actions/DeployToBcEnvironment@v7.2
        with:
          authContext: ${{ secrets[format('{0}_AuthContext', matrix.environment)] }}
          appFolders: ${{ vars.appFolders }}
          environmentName: ${{ matrix.environment }}
          appVersion: ${{ github.event.inputs.appVersion }}
          artifact: ${{ matrix.environment }}

  PostProcess:
    runs-on: windows-latest
    needs: Deploy
    steps:
      - name: Post Deployment Summary
        run: |
          Write-Host "Deployment completed for all selected environments."
