name: "Publish To Environment"

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to deploy (current, prerelease, draft, latest, version number or PR_<PR Id>)
        required: false
        default: 'current'
      environmentName:
        description: Environment mask (* for all, PROD* for PROD only, etc.)
        required: true

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  secrets: ${{ vars.ALGoUsedSecrets }}

jobs:
  Initialization:
    runs-on: windows-latest
    outputs:
      deploymentEnvironmentsJson: ${{ steps.setoutputs.outputs.deploymentEnvironmentsJson }}
      environmentMatrixJson: ${{ steps.setoutputs.outputs.environmentMatrixJson }}
    steps:
      - name: Read settings
        id: readsettings
        uses: microsoft/AL-Go-Actions/ReadSettings@v7.2

      - name: Debug Settings Output
        run: |
          Write-Host "deploymentEnvironments: ${{ steps.readsettings.outputs.deploymentEnvironments }}"
          Write-Host "environmentsMatrix: ${{ steps.readsettings.outputs.environmentsMatrix }}"

      - name: Set outputs
        id: setoutputs
        run: |
          echo "deploymentEnvironmentsJson=${{ steps.readsettings.outputs.deploymentEnvironments }}" >> $env:GITHUB_OUTPUT
          echo "environmentMatrixJson=${{ steps.readsettings.outputs.environmentsMatrix }}" >> $env:GITHUB_OUTPUT

  Deploy:
    name: Deploy to ${{ matrix.environment }}
    needs: Initialization
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJson(needs.Initialization.outputs.environmentMatrixJson) }}
    steps:
      - name: Deploy app
        uses: microsoft/AL-Go-Actions/DeployToBcEnvironment@v7.2
        with:
          authContext: ${{ secrets[format('{0}_AuthContext', matrix.environment)] }}
          appFolders: ${{ vars.appFolders }}
          environmentName: ${{ matrix.environment }}
          appVersion: ${{ github.event.inputs.appVersion }}
          artifact: ${{ matrix.environment }}

  PostProcess:
    runs-on: windows-latest
    needs: Deploy
    steps:
      - name: Done
        run: |
          Write-Host "✅ Deployment complete."

